// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "ChainBaby",
            "email": "ChainBaby"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/approveCoin": {
            "get": {
                "description": "代币授权",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "代币授权"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公链的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "消费者地址",
                        "name": "spender_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/burn": {
            "post": {
                "description": "销毁",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "销毁"
                ],
                "operationId": "10",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "合约地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "钱包私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "销毁数量",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/burnNft": {
            "post": {
                "description": "销毁Nft",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "销毁Nft"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nft地址",
                        "name": "nft_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "nft id",
                        "name": "token_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/checkAllowance": {
            "get": {
                "description": "查询检查授权",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "查询Token 检查授权"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公链的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "来源地址",
                        "name": "owner_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "消费者地址",
                        "name": "spender_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/createWallet": {
            "get": {
                "description": "创建钱包",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "创建钱包"
                ],
                "operationId": "1",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/getBaseAddress": {
            "get": {
                "description": "私钥转地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "私钥转地址"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公链的ID 0代表以太 1代表币安",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/getOa": {
            "get": {
                "description": "获取权限所属",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "波场获取账户权限Owner和Active"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "来源地址",
                        "name": "from_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/informReceive": {
            "post": {
                "description": "接收充值提现通知",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "接收充值提现通知"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安",
                        "name": "chain",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "区块号",
                        "name": "block_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "币名",
                        "name": "coin_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "合约地址",
                        "name": "contract_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "发起地址",
                        "name": "from_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "接收地址",
                        "name": "to_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "数量",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "txid",
                        "name": "txid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/issueSimpleCoin": {
            "get": {
                "description": "发布普通代币",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发布普通代币"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公链的ID 0代表以太 1代表币安",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "代币精度",
                        "name": "decimal",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币符号",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "总供应量",
                        "name": "total_supply",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/mintNft": {
            "post": {
                "description": "铸造Nft",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "铸造Nft"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nft地址",
                        "name": "nft_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "数量",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "价格",
                        "name": "price",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/multiSign": {
            "get": {
                "description": "多签",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "多签"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "操作地址",
                        "name": "current_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新权限拥有者",
                        "name": "new_owner",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/queryFeeBalance": {
            "get": {
                "description": "查询手续费币余额",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "查询手续费币余额"
                ],
                "operationId": "0",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户地址",
                        "name": "user_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/queryTokenBalance": {
            "get": {
                "description": "查询合约余额",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "查询合约余额"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "合约地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户地址",
                        "name": "user_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/queryTotalsupply": {
            "get": {
                "description": "查询Token总发行量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "查询Token总发行量"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公链的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "智能合约地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/tranferCoin": {
            "get": {
                "description": "转账代币",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转账代币"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "合约地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转出地址",
                        "name": "from_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标地址",
                        "name": "to_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "提币数量",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/transferFeeCoin": {
            "get": {
                "description": "转账手续费币",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转账手续费币"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "钱包的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转出地址",
                        "name": "from_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转入地址",
                        "name": "to_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "数量",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        },
        "/api/transferFromCoin": {
            "get": {
                "description": "授权转账代币",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权转账代币"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公链的ID 0代表以太 1代表币安 2代表波场",
                        "name": "chain_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代币地址",
                        "name": "token_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "代币数量",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "来源地址",
                        "name": "from_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标地址",
                        "name": "to_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "消费地址私钥",
                        "name": "private_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "$ref": "#/definitions/router.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "router.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ChainBaby",
	Description:      "ChainBaby",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
